spring:
  profiles:
    active: app1

  datasource:
    url: "jdbc:mysql://haloo.top:3306/chuangxu"
    username: "root"
    password: "ddb123698"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
    druid:
      min-idle: 5
      max-active: 30
  jackson:
      time-zone: Asia/Shanghai


  ## mybatis 配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml # 扫描mybatis的实现dao接口*.xml文件
